palabra = input("Ingrese una palabra: ")
a = palabra.count("a")
e = palabra.count("e")
i = palabra.count("i")
o = palabra.count("o")
u = palabra.count("u")
print(f"La vocal (a) aparece {a} veces en la palabra ingresada")
print(f"La vocal (e) aparece {e} veces en la palabra ingresada")
print(f"La vocal (i) aparece {i} veces en la palabra ingresada")
print(f"La vocal (o) aparece {o} veces en la palabra ingresada")
print(f"La vocal (u) aparece {u} veces en la palabra ingresada")